### ISSUE TITLE
how to use without pairing?

### ISSUE THREAD

**Issue by Frank-Buss** [rohitsangwan01/ble-peripheral-rust#1]
I tried the server example on Linux, and when I try to connect from it from a mobile phone with nRF Connect, a pairing request pops up. Is it possible to use it without pairing?

**Comment by Frank-Buss** [comment]
Looks like it is a configuration setting in BlueZ. When I follow the instructions here: https://github.com/bluez/bluez/issues/851#issuecomment-2464705878 then it doesn't ask to pair. Not sure if it is possible to disable the reverse discovery in the Rust application. If not, then just close this issue. But I think would be good to disable it by default, because usually the peripheral doesn't need to know the services of the central device (looks like a bad idea that BlueZ sets this to true by default).

**Comment by rohitsangwan01** [comment]
@Frank-Buss For linux we are using [bluer](https://github.com/bluez/bluer), if that library supports this configuration, then we can also try to implement here

**Comment by Frank-Buss** [comment]
Got an answer from bluez, it can't be changed by a program, needs to be in the config, so closing this issue, because works with the conf file.
