### ISSUE TITLE
doesn't work on Windows with a Broadcom USB dongle

### ISSUE THREAD

**Issue by Frank-Buss** [rohitsangwan01/ble-peripheral-rust#2]
I have a "Broadcom BCM20702 Bluetooth 4.0 USB Device" (says the device manager in Windows 10) and I get this error message when running the example:
```
 INFO  server > Service Added
 ERROR server > Error starting advertising: **BlePeripheralRust Windows Error**

        windows::core::Error: HRESULT(0x8007013C):
                Error { code: HRESULT(0x8007013C), message: "The device does not support the command feature." }
```
The same USB dongle works fine with Debian Linux with the example.

**Comment by Frank-Buss** [comment]
In general, the device works, e.g. I can list BLE devices and pair to them:

![Screenshot_20241128_104905](https://github.com/user-attachments/assets/597692c6-eeda-46f6-8a83-e90b5eb433df)

With which BLE adapter did you test it on Windows? I think the Broadcom chipset is pretty common, and the driver was integrated in Windows.

**Comment by rohitsangwan01** [comment]
if possible try to find which line causing this issue for you [here](https://github.com/rohitsangwan01/ble-peripheral-rust/blob/main/src/peripheral/winrt/peripheral_manager.rs#L61-L80)

**Comment by Frank-Buss** [comment]
When I comment the SetIsConnectable call, then there is no error, but I can't connect to it. Maybe it is a Windows problem, looks like there are problems with some USB dongles with peripheral mode:
https://stackoverflow.com/questions/56958687/bluetooth-le-peripheral-role-on-windows-10

But in this case probably a driver problem, because works fine in Linux. I guess not many manufacturers care about peripheral mode for Windows.

Do you have a working USB BLE dongle for connectable BLE peripherals, and what is the name in device manager, and the name for buying it?

**Comment by rohitsangwan01** [comment]
@Frank-Buss am using a Windows Laptop with Inbuilt bluetooth, and never faced this issue, never tried an external bluetooth dongle, if you ever found one, please share link, might be helpful for others as well
